name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: "mparvin/shadowsocks2:latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}
        file: Dockerfile
